### PR TITLE
Update koges.tsv

### PR DESCRIPTION
**Pull request by matentzn**

### CODE REVIEW

**Comment by beckyjackson** [comment]
I think these typos came from the actual cohort data dictionary. I would imagine they weren't indented though, so it's probably OK to fix? @jamesaoverton what do you think?

**Comment by matentzn** [comment]
Oh wow! Then its better to feed this back to @mcourtot and not merge this..

**Comment by matentzn** [comment]
My worry would be that the connection between their local data dictionary and the version hosted here would break.. after all, arent the labels the only things that keep them together?

**Comment by beckyjackson** [comment]
Let me double check. I need to find the original data dictionary. I'll let you know ASAP!

**Comment by beckyjackson** [comment]
OK - I lied, this is the one that I didn't copy the labels directly from because they had a PDF with just a list of labels so these typos *do* need to be fixed 😅 

This looks good to me, and I think we should merge it.

**Comment by beckyjackson** [comment]
Here's the original data dictionary, for reference: https://drive.google.com/file/d/1Hh_cG9HcZWXs70FEun8iDZZbt0H_J1oq/view

**Comment by matentzn** [comment]
Ok thats great then!

I saw some with special chars, like Womens health vs Women's health, and something with a greek letter as well..

**Comment by matentzn** [comment]
I agree to merge it as well, I give you the honors :P

**Pull request merged**
