### PR TITLE
Switch to gizmos in workflow

### LINKED ISSUE #176: Replace "robot tree" with Gizmos?
We are currently using a never-released ROBOT command to generate the tree browsers for the workflow (`robot tree`). This code hasn't been updated and I don't think there are any plans to update it.

@jamesaoverton would it be beneficial to replace `robot tree` with `gizmos.tree`? We would just need to also create the SQLite databases, which we aren't doing for anything else at this time. That said, the ROBOT trees are working fine (for now).

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #176 

Replace `robot tree` with `gizmos.tree` and `robot validate` with `gizmos.export` to generate HTML tables.

We're still using the old `robot-tree.jar` to create the GECKO structure for the real browser (`build/gecko_structure.json`). We could replace this with a custom script, but ROBOT is outputting the format that they need for `data/cohort-data.json`.

I had to add `[](./src/tree.sh)` to the DROID header in order for DROID to find the `src/tree.sh` script, otherwise it would say "resource not found" when trying to access the tree browsers from the index page ("View results"). I'm not sure if there's a better way to do this, but this at least doesn't show up on the main DROID page.

### CODE REVIEW

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
Let's get rid of robot-tree.jar by writing some custom Python.

**Comment by jamesaoverton** [comment]
Gizmos is missing from `requirements.txt`. When I tried to specify `ontodev-gizmos==0.1.5` I got `export.py: error: unrecognized arguments: -w stanza LIKE 'CHOP:%'`

**Comment by beckyjackson** [comment]
@jamesaoverton I've made a new release of gizmos and added it to the requirements, so the `-w` option should be available now.

**Comment by jamesaoverton** [comment]
Now I need Postgres and psycopg2 installed, which is a pain. Let's wait for the Gizmos SQLAlchemy branch to land, then return to this.

**Comment by jamesaoverton** [comment]
@beckyjackson When you get a chance please update Gizmos, then request my review again and I'll test it.

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
