### PR TITLE
Mapping suggestion pipeline

### PR DESCRIPTION
**Pull request by matentzn**
Had to delete the old draft and replace it by this, no changes since. In the general pipeline (not yet finalized, but something like):

image

This pull request covers step `5.`

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Pretty! :smile:

**Comment by matentzn** [comment]
Updated workflow (simplified, so this pull deals with step 4:


image

**Comment by matentzn** [comment]
@jamesaoverton This pull request is now read to be reviewed. As it is quite large, here some guidance on its contents:

**Changes to data:**
- data/ihcc-mapping-suggestions-zooma.csv is now data/ihcc-mapping-suggestions-zooma.tsv and a permanent file that contains the official mappings loaded into zooma. It is updated as part of `make all`.

**Changes to config:**
- Added two more requirements to python
- Some .gitignore changes
- factored most of the config of the mapping pipeline out to src/mapping-suggest/mapping-suggest-config.yml, which is a file probably worth looking at during review

**Code:**
- All **jupyter notebooks** are not part of our submission as Knocean - I used them for development and they contain additional code, which I have documented in src/mapping-suggest/README.md. They are useful for continuing development like trying different language / matching models etc, but revieweing them now is probably not necessary.
- all **python scripts** are annotated, linted and blacked (and part of some pipeline in the Makefile). Most of the common functionality can be found in lib.py. The python scripts are probably worth a quick look, but they work.
- The **sparql queries** are there two extract lexical data from the data dictionaries and GECKO with ROBOT query and probably not worth two close a look, but maybe a glance. 

**Pipeline:**
- src/mapping-suggest/Makefile contains only linting code. It does not harm anyone but I could delete it.
- Makefile is the only thing that I would suggest needs a really close review. The most questionable parts are:
   - Line 350 (installing requirements prior to pipeline run)
   - Line 316 (phony goal with dependencies)

 **Changes to documentation**
- src/mapping-suggest/README.md: Overview of mapping pipeline scripts for developers
- README.md: _NOT_ ready for review. I would just merge and I will continue working on it (starting now).

**Comment by beckyjackson** [comment]
A weird error that will probably never happen in real life (hopefully people aren't going and deleting IDs)... I ran the automated mapping, and then went in and deleted one ID:
image

Running the mapping again results in an error:
```
Traceback (most recent call last):
  File "src/mapping-suggest/id-generator-templates.py", line 76, in <module>
    highest_current_id = highest_current_id + 1
TypeError: can only concatenate str (not "int") to str
```

**Comment by matentzn** [comment]
Fixed now, was a typo.. Thanks for catching this!

**Comment by beckyjackson** [comment]
I found two minor bugs. I'm running Genomics England through the pipeline to see how it handles large data dictionaries and I ran into this:
```
Traceback (most recent call last):
  File "src/mapping-suggest/merge-mapping-suggestions.py", line 65, in <module>
    format_suggestions(suggestions) for suggestions in dfx["Suggested Categories"]
  File "src/mapping-suggest/merge-mapping-suggestions.py", line 65, in <listcomp>
    format_suggestions(suggestions) for suggestions in dfx["Suggested Categories"]
  File "/Users/tauber/github/DROID/projects/data-harmonization/workspace/validate-workflow/src/mapping-suggest/lib.py", line 217, in format_suggestions
    splitted = sorted([x.strip() for x in suggestions.split("|")], reverse=True)
```

It looks like there is a field in the data dictionary that did not get any suggestions and therefore the value is `NaN`. The reason this happened is because an ID was assigned to a blank row, so maybe we can add a check that the row has contents (e.g., a label) before giving it an ID... maybe even remove the blank row entirely.

image

I updated the `format_suggestions` method in `lib.py` and this seems to work fine (just so I could finish the workflow with GE), but you may want to handle it differently?
```python
def format_suggestions(suggestions):
    if not isinstance(suggestions, str):
        return ""
    splitted = sorted([x.strip() for x in suggestions.split("|")], reverse=True)
    covered = []
    filtered = []
    for suggestion in splitted:
            mapping = [x.strip() for x in suggestion.split(" ")][1]
            # print(mapping)
            if mapping not in covered:
                filtered.append(suggestion)
                covered.append(mapping)
    return " | ".join(filtered).strip()
```

**Comment by matentzn** [comment]
Thank you @beckyjackson thats exactly right. I made it even a bit stricter now. This check for id generation was already in place I hope:


```
for index, row in df.iterrows():
    value = row[COL_TERM_ID]
    if row[COL_LABEL] or (value.dtype == float and not np.isnan(value)):
        # print(str(value) + " " + str(row[COL_LABEL]))
        if (type(value) != str) or (not value.startswith(PREFIX)):
            ....
```

Can you check that you have merged the latest changes from this branch? Else I will have to revise that check! Thanks!

**Comment by matentzn** [comment]
Ok I think its done (@beckyjackson hopefully not too many conflicts with your branch).

image

We should probably rename task 5 to something like "Validate data dictionary with mappings and finalize"; this will then result, I assume, in these two things:

1. a ttl dump of the metadata in the metadata directory (this is what make uses to determine which data dictionaries to build)
2. a (validate) template tsv in the templates directory

Does this make sense?

**Comment by matentzn** [comment]
@jamesaoverton btw its now ready for review - sorry its a bit huge.

**Comment by beckyjackson** [comment]
I don't think "validate & finalize" makes sense as a single step because the admin will be rerunning validate until it passes. In my PR, I added a "prepare" task as part of the "Build files" task and that generated all the required content.

**Comment by matentzn** [comment]
You are totally right @beckyjackson sounds good to me!

**Comment by beckyjackson** [comment]
The mapper still seems to be assigning IDs to blank lines. You have an `if row[COL_LABEL] ... :` statement, but that doesn't seem to catch `NaN` values.  I changed that to be `if not pd.isnull(row[COL_LABEL]) ...` [here](https://github.com/IHCC-cohorts/data-harmonization/blob/mapping-suggest/src/mapping-suggest/id-generator-templates.py#L69) and it resolves this problem!

**Comment by matentzn** [comment]
Thank you! Sounds good to me!

**Pull request merged**
