### PR TITLE
Update GECKO lifestyle labels

### PR DESCRIPTION
**Pull request by beckyjackson**
This corresponds with the update here: https://github.com/IHCC-cohorts/GECKO/pull/27

@rosibaj we've updated the labels of the terms under "lifestyle and behaviours" to be less ambiguous. Side note, would you like to be notified whenever we change a term label or add a new term to GECKO? I don't want to overflow your inbox 🙂 

Here are the changes:

| Old Label | New Label |
| --- | --- |
drugs | recreational drug history
alcohol | alcohol use history
tobacco | tobacco use history
nutrition | dietary history
sleep | sleep history
oral health and hygiene | oral health history
physical activity | physical activity history

Unrelated to the JSON, I removed the `templates/index.tsv` because these are all terms coming from GECKO. They may change, and we can just use `robot export` to get the ID -> label.

### CODE REVIEW

**Comment by rosibaj** [comment]
@beckyjackson updates welcome :) helps me keep up-to-date on the data.

**Comment by beckyjackson** [comment]
Will do @rosibaj ! Do you want us to merge this update in now, or should we wait for you to make any necessary changes?

**Comment by rosibaj** [comment]
@beckyjackson you can merge now as i always point devs towards master for update - do you have a any more incoming updates that we can bundle in a single release or should i schedule this update?

**Comment by beckyjackson** [comment]
We have one more PR to update disease labels, so maybe just wait until that is in?
https://github.com/IHCC-cohorts/GECKO/pull/35

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
