### PR TITLE
Rework Makefile and README

### PR DESCRIPTION
**Pull request by beckyjackson**
WIP - updating documentation for #54

Note that TSVs were changed to CSVs because the multi-line definitions in many of the cohorts were causing problems in TSV format.

Instead of storing each data dictionary, we can now rely on the cohorts to add their data dictionaries to the ROBOT template master sheet and we will keep versioned copies of their ROBOT templates in the `templates` directory. There is no need for conversion scripts.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I like the "Adding a new cohort" section, but before that there should be a section on just setting up and running the code (unmodified).

**Comment by beckyjackson** [comment]
I think this is ready for review. I'd like to add more errors to the common errors section, but I just need to play around and break some things to do that.

I tried to rework the process to make it as simple as possible for somebody to add a new cohort - mostly limiting the changes that they have to make to the `Makefile`. There are some files that need to be added (metadata, templates), but to add a new cohort, the only change is to add a name to the cohorts list.

**Comment by jamesaoverton** [comment]
Great job!

A few changes:

- I'd like to keep the `data/` source files that we used (such as `data/genomics-england.xlsx`) in version control. I don't trust Google Drive to keep them in the same place forever. I'd also like to keep the `data/README.md`, and `data/random-data.json`.
- Please switch back to TSV, and improve `xlsx2tsv.py` to use the `csv module
- I'd like to keep the Browser code, if it's not too much trouble

**Comment by beckyjackson** [comment]
Do you want to maintain the browser code in this repo, or a separate repo?

**Comment by jamesaoverton** [comment]
I'd like the browser code in here, tucked away somewhere. As long as it doesn't make a mess.

**Comment by beckyjackson** [comment]
OK - browser files are back, and you can still run it with `make serve`.

Do we want to include this in the docs?

**Comment by jamesaoverton** [comment]
No, don't both documenting it.

**Comment by jamesaoverton** [comment]
Somehow I skipped over the description of this PR, where you said "we can now rely on the cohorts to add their data dictionaries to the ROBOT template". Maybe that's true going forward, but I want to keep the conversion scripts as examples. I added them back in to the source tree, but we don't need to talk about them in the README or the Makefile.

**Pull request merged**
