### PR TITLE
Add maelstrom script

### LINKED ISSUE #5: Generate OWL file for Maelstrom
- [x] Copy <https://github.com/maelstrom-research/maelstrom-taxonomies/blob/master/AreaOfInformation.yml> to `data/maelstrom.yml`
- [x] Update `data/README.md`
- [x] Create `src/maelstrom.py` script to generate a basic `build/maelstrom.tsv` ROBOT template
- [x] Create `metadata/maelstrom.ttl`, note the CC-by-nc-nd license
- [x] Update `Makefile` to build `build/maelstrom.owl` from the template and metadata

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #5 

Also using namespace `http://example.com/` here.

### CODE REVIEW

**Comment by beckyjackson** [comment]
We probably could use the `src/properties.tsv` template from #6 instead of including the two annotation properties in `maelstrom.ttl`. I can update this after we merge that one.

**Comment by jamesaoverton** [comment]
@beckyjackson Please update this PR.

**Comment by beckyjackson** [comment]
Updated and ready to merge

**Comment by jamesaoverton** [comment]
@beckyjackson Please update file locations if necessary, then let me know and I'll review.

**Comment by beckyjackson** [comment]
This is updated and should be ready to go!

**Pull request merged**
